### ISSUE TITLE
Debugging line needs to be taken out

### ISSUE THREAD

**Issue by peppersc** [tsugiproject/tsugi-php#24]
https://github.com/tsugiproject/tsugi-php/blob/30e4b5f06f2fa9e7bb742eb3e362e15a50d1f582/src/Core/LTIX.php#L1156

This line needs to be removed. It doesn't seem to cause a problem in "normal" operation, but it fouls things up for me in a special circumstance where I do a test LTI launch.

**Comment by csev** [comment]
I think this got cleaned up already. Thanks.
