### ISSUE TITLE
Update to the latest major version of Font Awesome

### ISSUE THREAD

**Issue by apcshields** [tsugiproject/tsugi-php#25]
It appears that all Tsugi models will be loaded with v.4(.7.0) of Font Awesome. Since Font Awesome *strongly* recommends not loading v.4 and v.5 side-by-side (https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#proofing), and v.5 has been out for more than a year, it would be good for the static files to be updated to this latest major version. ([Upgrade shims are available](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#shims), which, if I understand correctly, should mean existing modules would not need to be rewritten to remain compatible.)

Note: It does appear that there's a configuration option that one can use to replace the version hosted at static.tsugi.org, but since the option doesn't appear in the default config file, it seems unlikely most administrators will find it and make use of it.

**Comment by csev** [comment]
I would be quite happy to add 5.0 support if it would not break the existing markup.  So the strategy of the 5.0 + shims looks promising - let me take a look at the feasibility.  It should not be difficult.

**Comment by csev** [comment]
Thanks.   I will take a look at this.  I have another project that uses fontAwesome and I just switched it to using 5 + shim to get a little experience with it.   So far so good.  It is an easy fix to add it to static.tsugi.org <http://static.tsugi.org/> and then change Tsugi’s header code to use it.

I won’t remove the old files from static.tsugi.org <http://static.tsugi.org/> so folks with slightly behind versions of Tsugi will continue to work and those who upgrade won’t notice anything.

Thanks.

/Chuck

**Comment by apcshields** [comment]
That sounds reasonable.

May I ask why you don’t use their CDN?

**Comment by csev** [comment]
I am starting on this.   The reason that I don't use their CDN is that Tsugi can point at a local copy of tsugi-static so you can keep developing without a network connection.   Since Tsugi won't work at all without its static assets - it seemed like it was simpler to have one less dependency and the option of local development.  And static.tsugi.org is on the CloudFlare CDN - so it has free unlimited bandwidth already.

**Comment by csev** [comment]
Also, I produce PNG files for all the icons because LMS systems like Sakai, Canvas, etc need image files in things like Deep Linking responses, not just fontawesome names. So I convert all icons to PNGs and host them on Cloudflare as well.

**Comment by csev** [comment]
The default font-awesome is now 5.8.2 with the v4 shim in place.  If you want to hold back, simply add this to your config.php:

     $CFG->fontawesome = $CFG->staticroot . '/font-awesome-4.7.0'

https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#shims
https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself

Commit https://github.com/tsugiproject/tsugi/commit/dce86d1c80170b28e157bcdc03c99cac7fa10bef
